Changed user interface of the installation script: supports now long and short options and allows one to skipt the lengthy patch and afp installation check.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -34,13 +34,31 @@ ISABELLE_VERSION="Isabelle2017: October 2017"
 ISABELLE_URL="https://isabelle.in.tum.de/website-Isabelle2017/"
 AFP_URL="https://sourceforge.net/projects/afp/files/afp-Isabelle2017/afp-2018-08-14.tar.gz"
 
-ISABELLE=${1:-`which isabelle`}
+ISABELLE=`which isabelle`
 GEN_DIR=document-generator
-
+PROG=`echo $0 | sed 's|.*/||'`;
+ISABELLE_VERSION=`$ISABELLE version`
+SKIP="false"
 VARS=`$ISABELLE getenv ISABELLE_HOME_USER ISABELLE_HOME ISABELLE_TOOLS`
 for i in $VARS; do 
 	export "$i"
 done
+
+print_help()
+{
+    echo "Usage: $PROG [OPTION] "
+    echo ""
+    echo "Run ..."
+    echo ""
+    echo "  --help, -h                display this help message"
+    echo "  --isabelle, -i isabelle   isabelle command used for installation"
+    echo "                            (default: $ISABELLE)"
+    echo "  --skip-patch-and-afp, -s  skip installation of Isabelle/DOF patch for" 
+    echo "                            Isabelle and required AFP entries. USE AT"
+    echo "                            YOUR OWN RISK (default: $SKIP)"
+}
+
+
 
 exit_error() {
     echo ""
@@ -51,10 +69,9 @@ exit_error() {
 
 check_isabelle_version() {
     echo "* Checking Isabelle version:"
-    VERSION=`$ISABELLE version`
-    if [ "$VERSION" != "$ISABELLE_VERSION" ]; then
+    if [ "$ISABELLE_VERSION" != "$ISABELLE_VERSION" ]; then
         echo "  WARNING:"
-        echo "    The version of Isabelle (i.e., $VERSION) you are using"
+        echo "    The version of Isabelle (i.e., $ISABELLE_VERSION) you are using"
         echo "                        IS NOT SUPPORTED"
         echo "    by the current version of Isabelle/DOF. Please install a supported"
         echo "    version of Isabelle and rerun the install script, providing the"
@@ -71,7 +88,7 @@ check_isabelle_version() {
             exit_error
         fi
      else
-        echo "  Success: found supported Isabelle version ($VERSION)"
+        echo "  Success: found supported Isabelle version ($ISABELLE_VERSION)"
     fi
 }
 
@@ -189,11 +206,34 @@ install_and_register(){
 }
 
 
+
+while [ $# -gt 0 ]
+do
+    case "$1" in
+        --isabelle|-i)
+            ISABELLE="$2";
+            shift;;
+        --skip-patch-and-afp|-s)
+            SKIP="true";;
+        --help|-h)
+            print_help
+            exit 0;;
+        *)  print_help
+            exit 1;;
+    esac
+    shift
+done
+
+
 echo "Isabelle/DOF Installer"
 echo "======================"
 check_isabelle_version
-check_isa_dof_patch
-check_afp_entries
+if [ "$SKIP" = "true" ]; then
+  echo "  Warning: skipping installation of Isabelle patch and AFP entries."
+else
+  check_isa_dof_patch
+  check_afp_entries
+fi
 check_old_installation
 install_and_register
 echo "* Installation successful. Enjoy Isabelle/DOF, you can now build the session"
