Hide use of build script from users.

diff --git a/src/scripts/build b/src/scripts/build
--- a/src/scripts/build
+++ b/src/scripts/build
@@ -28,15 +28,107 @@
 # SPDX-License-Identifier: BSD-2-Clause
 
 set -e
-if [ ! -f $ISABELLE_HOME_USER/DOF/document-template/build_lib.sh ]; then
+OUTFORMAT=${1:-pdf}
+NAME=${2:-root}
+
+ROOT_NAME="root_$NAME"
+
+[ ! -f "$DIR/$ROOT_NAME.tex" ] && ROOT_NAME="root"
+
+if [ -f "$DIR/$ROOT_NAME.tex" ]; then 
     >&2 echo ""
-    >&2 echo "Error: Isabelle/DOF not installed"
+    >&2 echo "Error: Found root file ($DIR/$ROOT_NAME.tex)"
     >&2 echo "====="
-    >&2 echo "This is a Isabelle/DOF project. The document preparation requires"
-    >&2 echo "the Isabelle/DOF component from:"
-    >&2 echo "<isadofurl>"
+    >&2 echo "Isabelle/DOF does not use the Isabelle root file setup. Please check"
+    >&2 echo "your project setup. Your $DIR/isadof.cfg should define a Isabelle/DOF"
+    >&2 echo "template and your project should not include a root file."
+    >&2 echo ""
     exit 1
 fi
 
-cp $ISABELLE_HOME_USER/DOF/document-template/build_lib.sh .
-source build_lib.sh
+if [ ! -f isadof.cfg ]; then 
+    >&2 echo ""
+    >&2 echo "Error: Isabelle/DOF document setup not correct"
+    >&2 echo "====="
+    >&2 echo "Could not find isadof.cfg. Please upgrade your Isabelle/DOF document"
+    >&2 echo "setup manually."
+    exit 1
+fi
+
+TEMPLATE=""
+ONTOLOGY="core"
+CONFIG="isadof.cfg"
+while IFS= read -r line;do
+    fields=($(printf "%s" "$line"|cut -d':' -f1- | tr ':' ' '))
+    if [[ "${fields[0]}" = "Template" ]]; then 
+	TEMPLATE="${fields[1]}"
+    fi                      
+    if [[ "${fields[0]}" = "Ontology" ]]; then 
+	ONTOLOGY="$ONTOLOGY ${fields[1]}"
+    fi
+done < $CONFIG
+
+for o in $ONTOLOGY; do
+  >&2 echo "\usepackage{DOF-$o}" >> ontologies.tex;
+done
+
+ROOT="$ISABELLE_HOME_USER/DOF/document-template/root-$TEMPLATE.tex"
+if [ ! -f $ROOT ]; then 
+    >&2 echo ""
+    >&2 echo "Error: Isabelle/DOF document setup not correct"
+    >&2 echo "====="
+    >&2 echo "Could not find root file ($ROOT)."
+    >&2 echo "Please upgrade your Isabelle/DOF document setup manually."
+    exit 1
+fi
+
+cp $ROOT root.tex
+cp $ISABELLE_HOME_USER/DOF/latex/*.sty .
+cp $ISABELLE_HOME_USER/DOF/document-template/*.sty .
+cp $ISABELLE_HOME_USER/DOF/document-template/*.cls .
+
+# delete outdated aux files from previous runs
+rm -f *.aux 
+
+sed -i -e 's/<@>/@/g' *.tex 
+
+$ISABELLE_PDFLATEX root && \
+{ [ ! -f "$ROOT_NAME.bib" ] || $ISABELLE_BIBTEX root; } && \
+{ [ ! -f "$ROOT_NAME.idx" ] || $ISABELLE_MAKEINDEX root; } && \
+$ISABELLE_PDFLATEX root && \
+$ISABELLE_PDFLATEX root
+
+MISSING_CITATIONS=`grep 'Warning.*Citation' root.log | awk '{print $5}' | sort  -u`
+if [ "$MISSING_CITATIONS" != "" ]; then
+    >&2 echo ""
+    >&2 echo "ERROR (Isabelle/DOF): document referencing inconsistent due to missing citations: "
+    >&2 echo "$MISSING_CITATIONS"
+    exit 1
+fi
+DANGLING_REFS=`grep 'Warning.*Refer' root.log | awk '{print $4}' | sort  -u`
+if [ "$DANGLING_REFS" != "" ]; then
+    >&2 echo ""
+    >&2 echo "ERROR (Isabelle/DOF): document referencing inconsistent due to dangling references:"
+    >&2 echo "$DANGLING_REFS"
+    >&2 echo ""
+    exit 1
+fi
+if [ -f "root.blg" ]; then 
+    >&2 echo "BibTeX Warnings:"
+    >&2 echo "================"
+    >&2 grep Warning  root.blg | sed -e 's/Warning--//'
+    >&2 echo ""
+fi
+>&2 echo "Layout Glitches:"
+>&2 echo "================"
+>&2 echo -n "Number of overfull hboxes: "
+>&2 grep 'Overfull .hbox' root.log | wc -l
+>&2 echo -n "Number of underfull hboxes: "
+>&2 grep 'Underfull .hbox' root.log | wc -l
+>&2 echo -n "Number of overfull vboxes: "
+grep 'Overfull .vbox' root.log | wc -l
+>&2 echo -n "Number of underfull vboxes: "
+grep 'Underfull .vbox' root.log | wc -l
+>&2 echo ""
+
+exit 0
