Print messages to stderr to ensure visibility in logs.

diff --git a/document-generator/document-template/build b/document-generator/document-template/build
--- a/document-generator/document-template/build
+++ b/document-generator/document-template/build
@@ -28,17 +28,17 @@
 
 set -e
 if [ ! -f $ISABELLE_HOME_USER/DOF/document-template/build_lib.sh ]; then
-    echo ""
-    echo "Error: Isabelle/DOF not installed"
-    echo "====="
-    echo "This is a Isabelle/DOF project. The document preparation requires"
-    echo "the Isabelle/DOF framework. Please obtain the framework by cloning"
-    echo "the Isabelle/DOF git repository, i.e.: "
-    echo "    git clone https://git.logicalhacking.com/HOL-OCL/Isabelle_DOF"
-    echo "You can install the framework as follows:"
-    echo "    cd Isabelle_DOF/document-generator"
-    echo "    ./install"
-    echo ""
+    >&2 echo ""
+    >&2 echo "Error: Isabelle/DOF not installed"
+    >&2 echo "====="
+    >&2 echo "This is a Isabelle/DOF project. The document preparation requires"
+    >&2 echo "the Isabelle/DOF framework. Please obtain the framework by cloning"
+    >&2 echo "the Isabelle/DOF git repository, i.e.: "
+    >&2 echo "    git clone https://git.logicalhacking.com/HOL-OCL/Isabelle_DOF"
+    >&2 echo "You can install the framework as follows:"
+    >&2 echo "    cd Isabelle_DOF/document-generator"
+    >&2 echo "    ./install"
+    >&2 echo ""
     exit 1
 fi
 
